### ISSUE TITLE
The  Mean AP is 0.7190 when I test the model trained by example_train_384, is normal?

### ISSUE THREAD

**Issue by duanLH** [sanghoon/pva-faster-rcnn#10]
I  train the model in  example_train_384  using default parameter, by the result of test is only 0.719, Is this because of the trained dataset is not COCO+VOC07+VOC12?
thanks

**Comment by sanghoon** [comment]
Hi,
We haven't tried training these models with only VOC datasets
But the example prototxts are just samples.

If you want better mAP,
I suggest you increase stepsize, lower gamma (e.g. gamma 0.3165 and stepsize 300000) or adopt 'plateau' LR policy (#7).

**Comment by duanLH** [comment]
@sanghoon Oh, thank you very much
