### ISSUE TITLE
about cudnn

### ISSUE THREAD

**Issue by duanLH** [sanghoon/pva-faster-rcnn#13]
you said "Do NOT uncomment `USE_CUDNN := 1` (for running PVANET, cuDNN is slower than Caffe native implementation)", I want to know, the slower is include training and test? I train my net without cudnn, its so slow

**Comment by sanghoon** [comment]
I'm sorry we made a confusion here.
It's totally okay to uncomment USE_CUDNN if it makes your training faster.
It just means that commenting 'USE_CUDNN' worked faster in our computational environments.

I'll update README.

FYI, for our published results,
training of a network took 7~14 days with Titan X or GTX1080.

**Comment by happyharrycn** [comment]
I think it is possible to also make testing faster with cuDNN, although I have not got a chance to test it on PVANET. The performance issue is that cuDNN had bad implementations for certain convolutions (e.g. 1x1 convolutions with stride=1, which is used a couple of times in PVANET). You can still compile Caffe with cuDNN and put engine: CAFFE under convolution_param in these layers.

**Comment by jay2002** [comment]
@happyharrycn cool solution!
I have tried it and it really does work
