### ISSUE TITLE
Fail to convert full/original.model to full/test.model

### ISSUE THREAD

**Issue by John-HW-Cao** [sanghoon/pva-faster-rcnn#15]
Hi

I am trying to use the method in [https://github.com/sanghoon/pva-faster-rcnn/issues/5](https://github.com/sanghoon/pva-faster-rcnn/issues/5) to merge conv, bn, scale layers in original.model to a single conv layer in test.model.

But I failed. The file I obtained is different from full/test.model

And I check the full/original.model 
find that there are many zeros in original.model, which causes the failure.

So could anyone please tell me that if it is possible to do such a conversion by that method?
Is there another trick in the conversion?

**Comment by sanghoon** [comment]
Although we've done it with our own script (which wouldn't be generalized well enough),
there're some good discussions about it at #5.
I'm going to repeat the procedure with the script mentioned at #5

**Comment by sanghoon** [comment]
I've committed a simple script to merge 'Conv-BN-Scale' layers into a single Conv layer.
Please checkout 39570aa.
