### ISSUE TITLE
repeat experment for "example_train_384"

### ISSUE THREAD

**Issue by hengck23** [sanghoon/pva-faster-rcnn#18]
I want to verify my setup is correct or not.  I  intend to follow : 
https://github.com/sanghoon/pva-faster-rcnn/tree/master/models/pvanet/example_train_384,

Training for 100k iterations (toy)
tools/train_net.py 
    --gpu 0
    --solver models/pvanet/example_train_384/solver.prototxt
    --weights models/pvanet/imagenet/original.model
    --iters 100000
    --cfg models/pvanet/cfgs/train.yml
    --imdb voc_2007_trainval

For the 100k iterations (toy) above, what results do I get if I test on imdb voc_2007_test?

'' It is mentioned that this is not the same as the paper, so i do not have reference results for checking.
'' If anyone can share the results or train log files, it would be nice. Thanks!

**Comment by hengck23** [comment]
there are some answers for this:
https://github.com/sanghoon/pva-faster-rcnn/issues/7
https://github.com/sanghoon/pva-faster-rcnn/issues/10

Here are the results:
@duanLH        gets Mean AP is 0.7190
@xiaoxiongli   gets Mean AP is 0.7140

My training is still running. If I get the same results, that would be the performance and i will close the issue.

**Comment by hengck23** [comment]
Here is my results:
Mean AP is 0.7136

![results](https://cloud.githubusercontent.com/assets/5112846/19634389/200f895a-99ed-11e6-9fe9-4dc6d6887048.jpg)

**Comment by learntolearn11** [comment]
I have trained the experiment_finetue, but I can not find the train log file, where is the log file,?

**Comment by AITTSMD** [comment]
hi,I wonder how you draw the picture of the result? Can u give me some hints? the log file is in experiments/logs/

**Comment by etworker** [comment]
I have repeat the training process on train_384 with VOC2007, iteration times is about 1.1M, mAP on test set is about 72%, lower than 84% in paper.

maybe the reason is below?

> PVANet was trained by our in-house deep learning library, not by this implementation.
