### ISSUE TITLE
Why below "**post_nms_topn**" is set to 200?  

### ISSUE THREAD

**Issue by xiaoxiongli** [sanghoon/pva-faster-rcnn#24]
Dear All:

When i read models/pvanet/example_train_384_logo229/train.prototxt, i find that below "**post_nms_topn**" is set to 200, as i know, during training phase, the rpn network usually generate 2000 proposals per image, and in the inference phase, it will just generate about 200 or 300 proposals in order to save time.  

So i feel confused that during training phase, Why below "**post_nms_topn**" is set to 200?  

## C++ implementation of the proposal layer
 layer {
   name: 'proposal'
   type: 'Proposal'
   bottom: 'rpn_cls_prob_reshape'
   bottom: 'rpn_bbox_pred'
   bottom: 'im_info'
   top: 'rpn_rois'
   top: 'rpn_scores'
   proposal_param {
     ratio: 0.5 ratio: 0.667 ratio: 1.0 ratio: 1.5 ratio: 2.0
     scale: 3 scale: 6 scale: 9 scale: 16 scale: 32
     base_size: 16
     feat_stride: 16
     pre_nms_topn: 12000
     post_nms_topn: **200**                      <--------------**Why here post_nms_topn is 200 ?**
     nms_thresh: 0.7
     min_size: 16
   }
}

**Comment by sanghoon** [comment]
OMG!
If it was set to be 200 even in the training step,
it must be a bug in the prototxt.

**Comment by sanghoon** [comment]
This has been fixed in the new PVA prototxts
