### ISSUE TITLE
Mirrors of the models

### ISSUE THREAD

**Issue by dereyly** [sanghoon/pva-faster-rcnn#3]
Hi!
Thank you for your great paper! I found very intrusting that you catch all last ideas (in all levels of deep architecture) and implement it.

I want to run trained model, but there is some problem with dropbox: "This account's links are generating too much traffic and have been temporarily disabled!"

Do you have some mirrors like googleDrive?

**Comment by XikerWu** [comment]
I met this problem too. Would you please share a googleDrive link ? thx a lot~ @sanghoon

**Comment by sanghoon** [comment]
@kyehyeon will resolve this issue in a couple of days.

**Comment by kyehyeon** [comment]
Hi @dereyly @ngmanhei 
Mirrors are now available at the main page (https://github.com/sanghoon/pva-faster-rcnn/)

**Comment by XikerWu** [comment]
Wonderful! And thanks a lot~
