### ISSUE TITLE
Why using PowerLayer for identity mapping?

### ISSUE THREAD

**Issue by yijunCai** [sanghoon/pva-faster-rcnn#33]
Hi @sanghoon 
I notice that for short-cut connections, A PowerLayer is used for identity mapping（since both power and scale are set to 1） as follows:

layer {
  name: "conv2_3/input"
  type: "Power"
  bottom: "conv2_2"
  top: "conv2_3/input"
  power_param {
    power: 1
    scale: 1
    shift: 0
  }
}
layer {
  name: "conv2_3"
  type: "Eltwise"
  bottom: "conv2_3/3"
  bottom: "conv2_3/input"
  top: "conv2_3"
  eltwise_param {
    operation: SUM
    coeff: 1
    coeff: 1
  }
}

I'm wondering if "conv2_3/input" is neccessary. Why not  take "conv2_2" directly as bottom input for "conv2_3"?

**Comment by xiaoxiongli** [comment]
i think you can.

**Comment by sanghoon** [comment]
You can exclude the redundant Power layers.
I've added them so that I can easily generate the prototxt with my own script,
but they do nothing.

**Comment by zimenglan-sysu-512** [comment]
@sanghoon can you share your script which to generate the prototxt? thanks.
