### ISSUE TITLE
ProposalLayer2 layer in latest release?

### ISSUE THREAD

**Issue by hengck23** [sanghoon/pva-faster-rcnn#41]
In the prototxt file, i see "ProposalLayer" and "ProposalLayer2". However in "lib/rpn/proposal_layer.py", I only find class definition for "ProposalLayer".
Is "ProposalLayer2" missing?

https://github.com/sanghoon/pva-faster-rcnn/blob/master/models/pvanet/pva9.1/faster_rcnn_train_test_21cls.pt

layer {
  name: 'proposal'
  type: 'Python'
  bottom: 'rpn_cls_prob_reshape'
  bottom: 'rpn_bbox_pred'
  bottom: 'im_info'
  bottom: 'gt_boxes'
  top: 'rois'
  top: 'labels'
  top: 'bbox_targets'
  top: 'bbox_inside_weights'
  top: 'bbox_outside_weights'
  include { phase: TRAIN }
  python_param {
    module: 'rpn.proposal_layer'
    layer: 'ProposalLayer2'
    param_str: "{'feat_stride': 16, 'num_classes': 21, 'ratios': [0.333, 0.5, 0.667, 1, 1.5, 2, 3], 'scales': [2, 3, 5, 9, 16, 32]}"
  }
}
layer {
  name: 'proposal'
  type: 'Python'
  bottom: 'rpn_cls_prob_reshape'
  bottom: 'rpn_bbox_pred'
  bottom: 'im_info'
  top: 'rois'
  top: 'scores'
  include { phase: TEST }
  python_param {
    module: 'rpn.proposal_layer'
    layer: 'ProposalLayer'
    param_str: "{'feat_stride': 16, 'ratios': [0.333, 0.5, 0.667, 1, 1.5, 2, 3], 'scales': [2, 3, 5, 9, 16, 32]}"
  }
}

**Comment by sanghoon** [comment]
Hi @hengck23 ,
That's just a combination of 'ProposalLayer' and 'ProposalTargetLayer'.
I've fixed the prototxt and updated at f3a477316914e1d7a3467569584d15f0ec14611b (develop branch)
Please let me know if they don't work either.

**Comment by hengck23** [comment]
Thank you very much.
It works well.
