### ISSUE TITLE
where is the prototxt of new classification model？

### ISSUE THREAD

**Issue by XiongweiWu** [sanghoon/pva-faster-rcnn#42]
Thx for your excellent job! I notice you have update PVANet, and put new classification model in ./pva-faster-rcnn/models/pvanet/ folder. I wonder where is its corresponding prototxt? I guess it should be different with the one in ./pva-faster-rcnn/models/pvanet_obsolete/imagenet/. Waiting for your reply!

**Comment by sanghoon** [comment]
Hi @XiongweiWu 
I just added the prototxt for classification (69156c4bf5174ddbe7ad2448f5637d68230e81a4).
Please note that the provided model and prototxt are trained for 192x192 input images
