### ISSUE TITLE
Could you share your experiences in training pvanet?

### ISSUE THREAD

**Issue by KeyKy** [sanghoon/pva-faster-rcnn#48]
I use this code in training voc_2012_trainval+voc_2007_trainval and test in voc_2007_test. I can get the AP=0.7892. Could you share your experiences in training pvanet which can get the strong AP=0.849?

**Comment by sanghoon** [comment]
We've trained the network in three steps.
- Pre-training with ImageNet
- Training with COCO + VOC07 + VOC12 train/val
- Fine-tuning with VOC07 + VOC12 train/val

Additional training with the MS COCO dataset is essential for the SOTA results.

**Comment by KeyKy** [comment]
Thanks!
