### ISSUE TITLE
Python argument types in Net.copy_from(Net, str) did not match C++ signature:

### ISSUE THREAD

**Issue by solemnrole** [sanghoon/pva-faster-rcnn#51]
when i am runing the pvanet_obsolete/example_finetune model,loading the pretrained model,throwing the exception:"Python argument types in Net.copy_from(Net, str) did not match C++ signature",and idont know how to solve the exception.thanks!

**Comment by solemnrole** [comment]
i solved it!

**Comment by zhitongxiang** [comment]
I met this problem when I wanted to directly copy a pre-trained caffemodel using net.copy_from(), can you share your way to fix it ? Thanks very much

**Comment by innocenteureka** [comment]
can you share the way to fix it?I met this problem,too
