### ISSUE TITLE
Ask about deconvolution

### ISSUE THREAD

**Issue by ghost** [sanghoon/pva-faster-rcnn#6]
layer {
    name: "upsample"
    type: "Deconvolution"
    bottom: "conv5_4"
    top: "upsample"
    param { lr_mult: 0 decay_mult: 0}
    convolution_param {
        num_output: 384 kernel_size: 4 pad: 1 stride: 2 group: 384
        weight_filler: {type: "bilinear" } 
        bias_term: false
    }  
}

My question is why the layer's lr_mult is 0? 

And If the lr_mult is 0, why not use  "reshape"  to get upsample.

thanks !

**Comment by sanghoon** [comment]
Hi,

Here, the deconv. layer is initialized to be a bilinear upsampler and works just like it.

As far as I know, 'reshape' lets us manipulate blob dimensions without increasing or reducing the amount of data. (e.g. 32x32x3 image blob  => a vector with 3072 values) Therefore, it can't handle image or feature re-sizing.

Any corrections are welcome

**Comment by ghost** [comment]
@sanghoon Thanks，I forgot the "reshape" layer 's usuage. You are right!

good job!
