### ISSUE TITLE
Could you tell me pvanet AP(IoU=0.50:0.95) on coco?

### ISSUE THREAD

**Issue by KeyKy** [sanghoon/pva-faster-rcnn#60]
@sanghoon I want to fine tuning pvanet(trained on coco) on voc. However, i want to know your AP(IoU=0.50:0.95) of pvanet trained on coco. I get AP=0.258 on coco. Thanks!

**Comment by sanghoon** [comment]
Hi @KeyKy 
Sorry for a late reply.
We haven't tested it on the COCO dataset.
