### ISSUE TITLE
TypeError: im_detect() takes at least 3 arguments (2 given)

### ISSUE THREAD

**Issue by jonchoi** [sanghoon/pva-faster-rcnn#62]
Help? Error while running the demo.

![image](https://cloud.githubusercontent.com/assets/9872658/22758865/3d5859c6-ee05-11e6-9aae-8704948ba490.png)

**Comment by kecaiwu** [comment]
add this line before the function im_detect

"_t = {'im_preproc': Timer(), 'im_net' : Timer(), 'im_postproc': Timer(), 'misc' : Timer()} "

"im_detect(net, im, _t)"
