### ISSUE TITLE
Detection Speed 

### ISSUE THREAD

**Issue by GBJim** [sanghoon/pva-faster-rcnn#67]
Hi all:

Since this source code is slower than the version on the paper.  I want to know exactly the detection speed of this released PVANET.

I tested the detection speed on PVANET and PVANET-compressed on Tesla K80 with images of 
1280*720 resolution.

This is what I get:

PVANET -->                                5.68 FPS
PVANET-compress  -->              5.90  FPS

This is about 2.5 FPS faster than Faster-RCNN(VGG16) on my machine.
 
I want to confirm my detection time are consistent with your detection time. 
Please give some comments.  Thanks! :)

**Comment by vj-1988** [comment]
I tested the PVANET on TitanX gpu. I am also getting around 5-6 FPS for the images (net.forward() only).

**Comment by GBJim** [comment]
Thanks @vj-1988 !

**Comment by vj-1988** [comment]
@GBJim : According to [https://arxiv.org/pdf/1611.08588.pdf] , the PVANET is supposed to run above 20 FPS. I tried batching the images, but found that batching won't work in faster-rcnn frameworks (yet to be implemented). So getting 5-6 fps is not normal.

**Comment by GBJim** [comment]
@vj-1988:
As the author disclaimed on the README.md:
**This version of py-faster-rcnn is slower than our in-house runtime code (e.g. image pre-processing code written in Python)**
I am not expecting to get 20 FPS with Python implementation. This is also the reason I need to confirm the detection speed with others :)

By the way, what's the resolution of testing image on paper?

**Comment by twmht** [comment]
@GBJim 

I got 6FPS when testing.

My image resolution is 1920 * 1080

How about yours?

**Comment by vj-1988** [comment]
My test images were 1280*720 pixels

**Comment by twmht** [comment]
@vj-1988 

The author has claimed that this repo is written in python, thus slower than the paper's.
