### ISSUE TITLE
proposal_layer.py : 180 : invalid value encountered in greater_equal

### ISSUE THREAD

**Issue by Johnson-yue** [sanghoon/pva-faster-rcnn#84]
Hi, guys:
  when I run ./tools/test_pvanet.py the error is occur :  
`/pva-faster-rcnn1/tools/../lib/rpn/proposal_layer.py:180: RuntimeWarning: invalid value encountered in greater_equal
  keep = np.where((ws >= min_size) & (hs >= min_size))[0]`

So I track into the proposal_layer.py , I found this : 
 `Line 77  :     $scores is [nan nan ...nan] 
  Line 78  :     $bbox_deltas is also [nan nan .... nan] 
but ,
 Line 79   :     $im_info is fine not [nan]`  

I run code like this:
`cd $FRCN_ROOT
./tools/test_pvanet.py`

**Comment by Arthur-Shi** [comment]
@Johnson-yue I meet the same problem, how did you solve that?

**Comment by Johnson-yue** [comment]
@Arthur-Shi Sorry , I really forgot it. Maybe I had mistatke when I run it, so it was fixed by clone it again！
